apiVersion: v1
kind: Namespace
metadata:
  name: petclinic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
  labels:
    app: petclinic
spec:
  replicas: 2

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: petclinic

  template:
    metadata:
      labels:
        app: petclinic

    spec:

      containers:
        - name: petclinic

          image: medanyyy/pet-clinic:9-b3e886f

          # imagePullPolicy: Never

          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"

          # startupProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   failureThreshold: 30
          #   periodSeconds: 10

          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3

          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 60
          #   periodSeconds: 20
          #   timeoutSeconds: 5
          #   failureThreshold: 3

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: petclinic

spec:
  type: ClusterIP

  selector:
    app: petclinic

  ports:
    - name: http
      port: 80
      targetPort: 8080
